version: 2.1
orbs:
  rebar3: tsloughter/rebar3@0.5.4
workflows:
  build-test:
    jobs:
      - rebar3/compile
      - rebar3/ct:
          requires:
            - rebar3/compile
      - rebar3/cover:
          requires:
            - rebar3/ct
  test:
    post:
        - pip install codecov && codecov
