---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: >
      Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: [19.3, 20.3, 21.3, 22.3, 23.2]
        os: [ubuntu-latest]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Style review
        run: rebar3 lint
      - name: Cross reference analysis
        run: rebar3 as test xref
      - name: Static analysis
        run: rebar3 as test dialyzer
      - name: Common Tests
        run: rebar3 ct
      - name: Property tests
        run: rebar3 proper
      - name: Code coverage
        run: rebar3 as test do cover,covertool generate
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          files: _build/test/covertool/verl.covertool.xml
          name: ${{matrix.otp_vsn}}
